= Parameters

The parent key for all of the following parameters is `vcluster_provisioner`.


== `charts`

[horizontal]
type:: dictionary
default:: see `class/defaults.yml`

Configure the charts to deploy.


== `images`

[horizontal]
type:: dictionary
default:: see `class/defaults.yml`

Configure the images to use.


== `infrastructure`

[horizontal]
type:: dictionary

Configure the infrastructure.

=== `infrastructure.type`

[horizontal]
type:: string
default:: 'kubernetes'

The type of infrastructure to deploy to.

[NOTE]
====
Only type `kubernetes` and `openshift` are supported.
====

=== `infrastructure.namespace`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
infrastructure:
  namespace:
    annotations: {}
    labels: {}
    name: target-namespace
----

Configure the namespace of the target infrastructure.


== `controlPlane`

[horizontal]
type:: dictionary

Configure the vcluster statefull set.

=== `controlPlane.resources`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
controlPlane:
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 2Gi
----

Configure the resources for the vcluster component.

=== `controlPlane.storageClass`

[horizontal]
type:: string
default:: ''

The storage class to use for the vcluster component.

=== `controlPlane.storageSize`

[horizontal]
type:: string
default:: '5Gi'

The storage size to use for the vcluster component.


== `distribution`

[horizontal]
type:: dictionary

Configure the vcluster distribution.

=== `distribution.type`

[horizontal]
type:: string
default:: 'k3s'

Define the distribution to use.

[NOTE]
====
Only type `k8s`, `k3s` and `k0s` are supported.
====

=== `distribution.resources`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
distribution:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
----

Configure the resources for the distribution.


== `ingress`

[horizontal]
type:: dictionary

Configure the ingress component.

=== `ingress.enabled`

[horizontal]
type:: boolean
default:: true

Enable the ingress component.

=== `ingress.host`

[horizontal]
type:: string
default:: 'api.mycluster.local'

The host to use for the ingress component.

=== `ingress.annotations` and `ingress.labels`

[horizontal]
type:: dictionary
default:: {}

Configure the annotations and labels for the ingress component.


== `sync`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
sync:
  fromHost: {}
  toHost: {}
----

Configure the sync configuration, see https://www.vcluster.com/docs/vcluster/next/configure/vcluster-yaml/sync[vCluster Sync].


== `helmValues`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
helmValues:
  vcluster: {}
----

Override the default values for the helm chart.


== Example

[source,yaml]
----
namespace: example-namespace
----
